Import("env")

env.Library(
    target='index_entry_comparison',
    source=[
        'index_entry_comparison.cpp',
        ],
    LIBDEPS=[]
    )

env.Library(
    target='bson_collection_catalog_entry',
    source=[
        'bson_collection_catalog_entry.cpp',
        ],
    LIBDEPS=[]
    )

env.CppUnitTest(
    target = 'record_store_test',
    source = [
        'record_store_test.cpp',
    ],
    LIBDEPS = [
        '$BUILD_DIR/mongo/coredb',
        '$BUILD_DIR/mongo/coreserver',
        '$BUILD_DIR/mongo/mongocommon',
        '$BUILD_DIR/mongo/serveronly',
        '$BUILD_DIR/mongo/db/concurrency/lock_mgr',
    ],
    NO_CRUTCH = True
)
